# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9b1d7574fe125102917880fdfe2a8dd4"
name = "wishlist-app-utk"
handle = "wishlist-app-utk"
application_url = "https://your-railway-app.up.railway.app"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_app_proxy,read_products,read_customers,write_customers"

[app_proxy]
url = "https://your-railway-app.up.railway.app/api/proxy"
subpath = "utk"
prefix = "apps"


[auth]
redirect_urls = [
  "https://your-railway-app.up.railway.app/auth/callback",
  "https://your-railway-app.up.railway.app/auth/shopify/callback",
  "https://your-railway-app.up.railway.app/api/auth/callback"
]
[pos]
embedded = false
